# Generated by Django 4.2 on 2023-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="slug",
            field=models.SlugField(default="question"),
            preserve_default=False,
        ),
    ]
